example10/conduit.c
example10/datastore.py

This PR fixes a problem where stdout from a Python program does not make into kvs unless it exits. Along with that, I add a couple of commits to improve logging.

ex10: Add a workaround for stdout buffering mishandling

---

README.md
example1/README.md

This PR makes changes to README.md to include the following formatting changes:
- Numbers for each step in the sub-examples instead of bullet points.
- Markdown code format for the command line steps in each example instead of bold font.

doc: Updating README.md in example1

---

example2/README.md
example2/submitter.lua
example2/submitter.py
example2/submitter2.lua
example2/submitter2.py

This PR introduces minor changes to the following files:
1. **README.md**
- Numbers for each step in the sub-examples instead of bullet points.
- Markdown code format for the command line steps in each example instead of bold font.
2. **submitter.py** and **submitter2.py**
- When running the original scripts as is, I would get a "failed" job state when running `flux wreck ls`; see example below:
```
bash-4.2$ flux wreck ls
ID NTASKS STATE                    START      RUNTIME    RANKS COMMAND
1      4 failed     2019-10-07T10:14:49       0.174s    [0-1] compute.py
2      1 failed     2019-10-07T10:14:49       0.137s        2 io-forwarding
```
Adding `./` in front of the scripts to …

doc: Updating README.md, submitter scripts in example2

---

example3/README.md

This PR makes minor formatting changes to the format of **README.md**:
- Numbers for each step in the sub-examples instead of bullet points.
- Markdown code format for the command line steps in each example instead of bold font.
- Example output after a successful `flux submit` to make it clear we are attaching to a job's running/completed output with its job ID

doc: Updating README.md in example3/

---

example4/README.md
example4/R_lite.lua
example4/ensemble.sh

This PR introduces minor changes to the following files:
1. **README.md**
- Numbers for each step in the sub-examples instead of bullet points.
- Markdown code format for the command line steps in each example instead of bold font.
- Removed LC path from `flux` command
2. **ensemble.sh**
Added `./` in front of the scripts to be run in **ensemble.sh** to fix the `command not found` errors when running the script as is.
3. **R_lite.lua**
Changed the `require` statement of `cpuset` from 
`local cpuset = require 'flux.cpuset'`
to
`local cpuset = require 'flux.affinity'.cpuset` (`cpuset` is a member of `flux.affinity`)

doc: Updating README.md and scripts in example4/

---

example7/README.md

Made the following changes to `README.md`:
- Added table listing of equivalent commands for unsetting `FLUX_SCHED_OPTIONS`
in both tcsh, and bash/zsh shells.
- Fixed formats for instructions for each step in the walkthrough.

doc: Update README.md in example7/

---

example6/README.md
example6/ensemble.sh
example6/parent.sh

This PR introduces the following changes to three files in this repository:
**README.md**
Changed format of instructions on example code; set example instructions for unsetting environment variable `FLUX_SCHED_OPTIONS` in both tcsh and bash/zsh shells.
**parent.sh**
Changed `NCORES` in from 216 to 3, and removed `-s1` flag from `flux submit` command.
**ensemble.sh**
Changed `NJOBS` from 5000 to 750.

doc: Update README.md and example scripts in example6/

---

example3/README.md

This PR makes the following changes to `example3/README.md`:
- Add numbered steps instead of bullet points for command line instructions
- Add bash/zsh syntax for setting `FLUX_SCHED_OPTIONS`
- Remove LC Path for Flux executable
- Change format of command line instructions from **bold** font to `in-line code`
- Add example output after `flux mini submit`

example3 doc: Update README.md to match new execution system commands

---

example5/README.md
example5/compute.lua
example5/io-forwarding.lua

Oops, I'm sorry! When submitting all of these PR's I must have forgotten to submit this specific example. 
This PR makes the following changes to **README.md**:
- Added numbers to instructions
- Added code format to step-by-step instructions
- Changed allocation for `io-forwarding.lua` script 
- Added a note to user to inform them that output might not show up until all tasks complete.

[flux-core v0.11] doc: Update README.md in example5/

---

example5/README.md
example5/app.c
example5/compute.lua
example5/io-forwarding.lua

This PR makes the following changes:
1. **README.md**:
- Update instructions to include setting `PKG_CONFIG_PATH` and `FLUX_MODULE_PATH`
- Add numbered instructions instead of bullet points
- Change instructions from **bold** font to `in-line code`
2. **app.c**
- Update use of `flux_respond()` to remove unnecessary third parameter
3. **compute.lua** and **io-forwarding.lua**
- Add I/O flushing to both scripts 
Thanks @dongahn for helping me debug these issues!

[flux-core v0.13] example5: Update README, app.c, and Lua scripts

---

example9/README.md
example9/kvsput-usrdata.py

This PR makes the following changes:
**kvsput-usrdata.py**
- update script to comply with new KVS Python interface 
- remove unneeded `FLUX_JOB_KVSPATH` environment variable from script
**README.md**
- update format of instructions from **bold** font to `in-line` code
- change order of instructions from bullet points to numbered instructions
- add descriptions for some of the instructions dealing with KVS interface and added a **Notes** section that goes into some detail about the commands in `kvsput-usrdata.py`

[flux-core v0.13] example9 update: Update kvsput-usrdata.py, README.md

---

example7/README.md
example7/bookkeeper.py
example7/compute.py
example7/io-forwarding.py

This PR proposes the following changes:
1. **README.md**
- Update format of instructions from bullet points to numbered instructions
- Remove instruction to set `FLUX_SCHED_OPTIONS` environment variable
- Update example output to match new **bookkeeper.py** script
2. **bookkeeper.py**
- Update job submissions in script to comply with new Python bindings, create new callback function that waits for jobs to transition to `INACTIVE` state
3. **compute.py** and **io-forwarding.py**
- Blacken both scripts

[flux-core v0.13] example 7 update: Update bookkeeper script, README, blacken Python scripts

---

example9/README.md

Thanks @SteVwonder for pointing out the incorrect header on example 9's **README.md** (Issue #48). This small PR fixes that by changing the header from **Example 10** to **Example 9**.

[flux-core v0.13] example9: fix incorrect title in header

---

example10/README.md
example10/compute.py
example10/submitter_sliding_window.py
example10/submitter_wait_any.py
example10/submitter_wait_in_order.py

This PR looks to add a new example to our workflow-examples repo based on the idea proposed by @garlick in Issue #45. This example contains three parts:
- **submitter_wait_any.py**: job submit/wait for completion in any order
- **submitter_sliding_window.py**: job submit/wait and keep at most a number of jobs active
- **submitter_by_id.py**: job submit/wait for completion in order by jobid
The **submitter** scripts were essentially copy-and-paste from the examples @garlick provided, which can be found here: [waitany](https://github.com/flux-framework/flux-core/blob/master/t/job-manager/submit-waitany.py), [sliding_window](https://github.com/flux-framework/flux-core/blob/master/t/job-manager/submit-sliding-window.py), and [by_id](https://github.com/flux-framework/flux-core/blob/master/t/job …

add new example: Python Job Submit/Wait Example

---

example1/compute.py
example1/io-forwarding.py
example10/compute.py
example10/submitter_sliding_window.py
example10/submitter_wait_any.py
example10/submitter_wait_in_order.py
example2/compute.py
example2/io-forwarding.py
example2/submitter.py
example2/submitter2.py
example7/bookkeeper.py
example7/compute.py
example7/io-forwarding.py
example8/README.md
example8/kvsput-usrdata.py
example9/compute.py
example9/datastore.py

This PR makes the following changes:
- update shebang to use python3 instead of python2
- blacken Python files in examples
It also makes a small correction in example8 which I failed to realize a couple of PR's ago:
- change the title number of example8's **README** from example 9 to example 8
- change `flux submit` instruction to `flux mini submit`

misc: update shebang to python3, fix example8 README

---

README.md

This tiny PR removes "Lua" from _example2_'s description in the top-level **README.md** since the Lua bindings have been deprecated.

top-level README: remove "Lua" from example 2 description

---

example7/README.md
example7/bookkeeper.py

This PR addresses issue #59 and updates the semantics of the command line argument in **bookkeeper.py**. When a job bundle number _x_ is specified, _x_ instances of **compute.py** and _x_ instances of **io-forwarding.py** are submitted. If no argument is passed, than 10 jobs (5 of each) are submitted. That note is also made in **README.md**:
> 3. Run the bookkeeper executable along with the size of the jobs bundle (if no size is specified, 5 instances of **compute.py** and 5 instances of **io-forwarding,py** jobs are submitted):

example7: update semantics of command line args, update README

---

job-submit-wait/README.md
job-submit-wait/submitter_sliding_window.py
job-submit-wait/submitter_wait_any.py
job-submit-wait/submitter_wait_in_order.py

In response to `flux-framework`'s recent PR [#2719](https://github.com/flux-framework/flux-core/pull/2719), example10 needs to change its parameters when using `job.submit`. This PR changes the args in `job.submit` and replaces `flags` with `waitable=True`.

example10: change args in job.submit

---

hierarchical-launching/ensemble.sh
hierarchical-launching/parent.sh
job-ensemble/README.md
job-ensemble/ensemble.sh

As mentioned in #65, the the `flux job drain` and `flux job undrain` commands need to be updated to `flux-queue drain`. This PR makes that update in both the **job-ensemble** and **hierarchical-launching** examples.

job-ensemble,hierarchical-launching: update examples with new flux-queue command

---

async-bulk-job-submit/README.md
async-bulk-job-submit/bulksubmit.py

Mentioned in #66: **bulksubmit.py** needed to be updated. This PR replaces the `flags` parameter in `job.submit_async` with `waitable=True`. 
@dongahn you had also mentioned in your [comment](https://github.com/flux-framework/flux-core/issues/2915#issuecomment-620889771) that you commented out the `sys.stdout.write(s)` line; however I believe that line just prints out the progress bar, right? I tested it with the current version of flux-core and it seemed to work just fine. If you still want it removed, just let me know and I'd be happy to remove it.

async-bulk-job-submit: update bulksubmit.py

---

.github/workflows/main.yml
.mergify.yml

This PR adds mergify and Github actions to the repository so that PR's can automatically be merged. The Github Actions file is pulled from the other flux-framework projects, and **.mergify.yml** is pulled from flux-accounting (without the status check for Python versions, since not all examples are exclusively Python). I believe the `black` and `flake8` Python-specific actions should exit safely regardless of whether there is Python code present or not. 
The .mergify.yml file is pretty barebones right now, but I'm not sure if there are additional checks we would want to perform on a new/edited example in this repository. 
Fixes #71

repo: add mergify, Github actions to repository 

---

job-submit-api/README.md
job-submit-cli/README.md
synchronize-events/README.md

**Problem:** As noted in #74, some of the examples are still using `flux job list`.
This PR updates the command to `flux jobs` in a a number of the examples. 
Fixes #74

flux jobs: update examples to use 'flux jobs' instead of 'flux job list

---

job-cancel/README.md
job-cancel/submitter.py

This PR adds a new workflow example to demonstrate Flux's `job cancel` Python binding. It consists of one script that submits a `sleep 180` job, cancels it, and lists the job id after.
For now, the output from `submitter.py` just lists the submitted job id, the same ID after it gets cancelled, and the list of job IDs using `flux.job.job_list(flux_handle)`:
```
Submitted job: 10080741228544
Cancelled job: 10080741228544
Job IDs: [{'id': 10080741228544}]
```
I'm trying to think if there is a better way to showcase the `cancel` feature with the Python script?

Add a job-cancel example

---

Makefile
README.md
async-bulk-job-submit/README.md
conf.py
data-conduit/README.md
hierarchical-launching/README.md
index.rst
job-cancel/README.md
job-status-control/README.md
job-submit-api/README.md
job-submit-cli/README.md
job-submit-wait/README.md
kvs-python-bindings/README.md
requirements.txt

Adds an `index.rst` that properly links things up via ReST.  Makes the headers across the examples more uniform to improve the look of the toctree.

Add Sphinx and ReadTheDocs Support

---

job-cancel/README.md
job-cancel/submitter.py

Problem: The spelling of "canceled" is inconsistently
used in flux.  Sometimes the British spelling "cancelled" is
used and othertimes the American spelling "canceled" is used.
Solution: Change all spellings of "cancelled" to "canceled".
Fixes #83

Globally standardize spelling of "canceled"

---

README.md
async-bulk-job-submit/README.md
async-bulk-job-submit/bulksubmit.py
async-bulk-job-submit/bulksubmit_executor.py
job-status-control/README.md
job-status-control/bookkeeper.py
job-submit-wait/README.md
job-submit-wait/compute.py
job-submit-wait/submitter_sliding_window.py
job-submit-wait/submitter_wait_any.py
job-submit-wait/submitter_wait_in_order.py

This PR adds examples of using `FluxExecutor` and  `FluxEventExecutor` flux-framework/flux-core#3468. In particular, I modify the job-submit-wait examples so that they only use `FluxExecutor`, I add an example of bulk submission with `FluxExecutor` to async-bulk-job-submit (but I leave the original example), and I modify the job-status-control example to use `FluxEventExecutor`. 
In these three cases I think the executor implementation is easier to explain; in the other Python examples I don't think the executor adds anything, so I didn't modify them.
As unrelated issues I also fix #82 and add the programming language into the title of each example in the README, since as a user the first thing I want to know is whether I will be able to understand or use the code in the examples (and I …

Add FluxExecutor examples

---

README.md
async-bulk-job-submit/README.md
comms-module/README.md
data-conduit/README.md
hierarchical-launching/README.md
index.rst
job-cancel/README.md
job-ensemble/README.md
job-status-control/README.md
job-submit-api/README.md
job-submit-cli/README.md
job-submit-wait/README.md
kvs-python-bindings/README.md
synchronize-events/README.md

Adds some additional directions to the READMEs and the sphinx documentation, specifying that to run the examples you have to clone the repo. Adding links to the source code would also work, but I think cloning the repo and changing your working directory is a lot easier than copying each file one by one.

Docs: specify how to get example source code
